### ISSUE TITLE
Padani a:Drake (5.0-5.03) v mapě

### ISSUE THREAD

**Issue by pangogo** [ludekv/a-drake#308]
a:Drake od verze 5.x neustále padá při zoomování či posunu prstem bitmapové databázové mapy či vektorové mapy (plus verze na Samsung Galaxy S2 a normální verze na Samsung Galaxy Ace2). Děje se tak pokud běží GPS a a:Drake naviguje ke keši (červená čára). Pokud je vyplá GPS a  a:Drake nenaviguje, zdá se to být stabilnější. Obě mapy jsme bez problémů používal na starších 4.x verzích a:Drake. V podstatě není možnost se podívat na keš v mapě, aby mi to nespadlo. Činí to tak a:Drake téměř nepoužitelný (verzi 4 jsem provozoval třeba 5 hodin bez pádu, verzi 5.x tak 5 minut). 
Prosím o nějaké řešení (třeba i dát na Google Play starší verzi 4.x).

**Comment by PontiacCZ** [comment]
Bylo by fajn přijít na kloub tomu padání, protože díky pádu po sobě a:Drake zapomíná uklidit - zůstávají tak úvodní souřadnice přepsané finálními a nesmaže se referenční waypoint "Original location". Právě se mi to u jedné keše přeneslo do Geogetu a když jsem zapřemýšlel, proč to tam mám, tak jsem přesvědčen, že důvod je právě toto "neskutečné padání". :)

**Comment by gord951** [comment]
PontiacCZ, neni ten prenos spis zpusoben tim, co jsem psal ja ohledne GPX souboru? Podle me to s padanim souviset nemuze.

Co se padani tyka, prisuzoval bych to nejake praci s mapou nebo GPS. Pokud je GPS vypnuta, padani se nekona nebo jen velmi zridka (alespon u me).

**Comment by PontiacCZ** [comment]
Je pravda, že vždy, když jsem přepínal mezi vektorovou/satelitní mapou nebo otevíral kešku z mapy (typické případy, kdy mi to padne), jsem měl vždy zapnutou GPS. S ní to skutečně souviset může.

Ohledně přenosu - možné to je, teď si nevybavuju, jaký je mechanismus použití finálních souřadnic jakožto úvodních.

**Comment by pangogo** [comment]
Dodavam, ze u verze 5.04 zadna zmena:(
Nekdy dokonce staci se prepnout mezi kesemi (v mape vybrat jinou) a opet to spadne.
Jeste par nedel a po letech prejdu na jiny software:(

**Comment by pangogo** [comment]
Mam jeden log file z Catlog k danemu problemu. Zde je obsah (neslo mi to pripojit jako txt soubor k tomuto logu - pise to, ze "Attaching documents requires write permission to this repository"):

10-30 21:05:03.925 D/VoldCmdListener(1900): asec fspath cz.adrake.plus-2
10-30 21:05:03.925 D/MountService(3364):  :::: getSecureContainerFilesystemPath :: id = cz.adrake.plus-2, result = /mnt/secure/asec/cz.adrake.plus-2.asec
10-30 21:22:29.430 I/ActivityThread(14020): Pub cz.adrake.plus.QSSuggestionProvider: cz.adrake.utils.QSRecentSuggestionsProvider
10-30 21:22:46.450 I/NotificationService(3364): cancelToast pkg=cz.adrake.plus callback=android.app.ITransientNotification$Stub$Proxy@4293c0a0
10-30 21:22:54.785 D/ApplicationPolicy(3364): isStatusBarNotificationAllowed: packageName = cz.adrake.plus
10-30 21:22:54.985 D/Sensors (14020): Remain listener = cz.adrake.GcDetMain$1@42c74dc0
10-30 21:23:02.380 I/NotificationService(3364): cancelToast pkg=cz.adrake.plus callback=android.app.ITransientNotification$Stub$Proxy@42766200
10-30 21:23:18.295 I/NotificationService(3364): cancelToast pkg=cz.adrake.plus callback=android.app.ITransientNotification$Stub$Proxy@4287d788
10-30 21:23:29.530 I/NotificationService(3364): cancelToast pkg=cz.adrake.plus callback=android.app.ITransientNotification$Stub$Proxy@428831c8
10-30 21:23:36.210 D/Sensors (14020): Remain listener = cz.adrake.GcDetMain$1@42c74dc0
10-30 21:23:36.215 D/Sensors (14020): Remain listener = cz.adrake.GcDetMain$1@42c74dc0
10-30 21:23:36.345 D/ApplicationPolicy(3364): isStatusBarNotificationAllowed: packageName = cz.adrake.plus
10-30 21:23:37.915 I/dalvikvm(14020):   at cz.adrake.map.GenericMap.getTileBitmap(GenericMap.java:149)
10-30 21:23:37.920 I/dalvikvm(14020):   at cz.adrake.map.MapView.drawTile(MapView.java:718)
10-30 21:23:37.920 I/dalvikvm(14020):   at cz.adrake.map.MapView.onDraw(MapView.java:549)
10-30 21:23:37.945 E/AndroidRuntime(14020):     at cz.adrake.map.GenericMap.getTileBitmap(GenericMap.java:149)
10-30 21:23:37.945 E/AndroidRuntime(14020):     at cz.adrake.map.MapView.drawTile(MapView.java:718)
10-30 21:23:37.945 E/AndroidRuntime(14020):     at cz.adrake.map.MapView.onDraw(MapView.java:549)
10-30 21:23:46.725 I/ActivityManager(3364): Process cz.adrake.plus (pid 14020) (adj 0) has died.
10-30 21:23:51.865 I/ActivityThread(14236): Pub cz.adrake.plus.QSSuggestionProvider: cz.adrake.utils.QSRecentSuggestionsProvider

**Comment by PontiacCZ** [comment]
Kdyby se tak povedlo opravit tuto nepříjemnost, to by bylo bájo. Stále to při otevírání keší z mapy nebo zoomování v mapě padá jak ovoce na podzim...

**Comment by pangogo** [comment]
Já v to doufám, můžu dodat spoustu dalších logů, které jsou úplně stejné, jako už uvedený.
Protože jsme si na aDrake už zvykl, nerad bych ho opouštěl, ale fakt je,že už mi práce s ním poslední dobou leze krkem. Dřív jsem celý den podle něj chodil jako s mapou, teď se to vůbec nedá použít. Odlov jedné keše jsou tak 2-3 pády.Jsem taky programátor (i když asi ne tak dobrý :) a vím, že častokrát najít zdroj padání je problém. Klidně bych se tedy vrátil ke starší (fungující) verzi. Proč tohle není možné? Nešlo by nám, potrefeným, poslat apk se starší verzí?
